### ISSUE TITLE
Replace Docker autobuilds with GitHub actions

### ISSUE THREAD

**Issue by niklasf** [niklasf/fishnet#187]
After https://www.docker.com/blog/changes-to-docker-hub-autobuilds/

**Comment by niklasf** [comment]
Pasting chat excerpts with additional info:

> currently, the github actions build produces standalone binaries
> and the docker autobuild produces docker images
> so people can use whichever they prefer
> the github actions build could also push docker images. that's currently my favored replacement for docker autobuilds

> Ah, I fount it. https://hub.docker.com/r/niklasf/fishnet

> yep. pushing to the master branch of the git repository will update niklasf/fishnet:latest
> pushing a tag v2.3.4 will update niklasf/fishnet:2.3.4, niklasf/fishnet:2.3 and niklasf/fishnet:2

**Comment by gbedoya** [comment]
Hi. I'm going to submit a PR in the coming days. However, prior to the pull-request would you be able to create the following Github repo secrets. This ensures the PR builds successfully during review.

```
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```
To create a new token, go to Docker Hub Settings and then click New Access Token.
